spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    url: jdbc:mysql://host.docker.internal:3307/accounts
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8500'